[__many__]
type = option(emission, activity, geometry, default=geometry)
inventory = string(default=None)
file_name = string
file_path = string
file_info_path = string
set = string(default="")
filter = string(default="")
scenarios = force_list(default=list())
vertical_distributions = force_list(default=list())
